image: node:7.2.0

clone:
  depth: 100000

pipelines:
  default:
    - step:
        script:
          - git config user.email "<user.email>"
          - git config user.name "<user.name>"
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.5
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn test -- --skip
          - yarn version --new-version minor
          - yarn build
          - git add -A
          - git commit -m "RELEASE VERSION $(node -p -e "require('./package.json').version")"
          - git push origin master
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
